version: '3.8'


services:
 mariadb-db:
   image: mariadb:10.11
   container_name: mariadb-db
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: ""
     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
     MYSQL_DATABASE: db_spotia
   networks:
     - network-spotia
   healthcheck:
     test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root"]
     interval: 10s
     timeout: 5s
     retries: 20


 eureka-server:
   build: ./eureka/eureka
   container_name: eureka-server
   ports:
     - "8761:8761"
   networks:
     - network-spotia
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
     interval: 15s
     timeout: 5s
     retries: 10
     start_period: 30s


 api-gateway:
   build: ./gateway/gateway
   container_name: api-gateway
   ports:
     - "8080:8080"
   environment:
     EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
     SPRING_PROFILES_ACTIVE: dev
   networks:
     - network-spotia
   depends_on:
     eureka-server:
       condition: service_healthy


 clientes-service:
   build: ./clientes/clientes
   container_name: clientes-service
   environment:
     SPRING_PROFILES_ACTIVE: dev
     EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
     DATABASE_HOST: mariadb-db
     GATEWAY_URL: http://localhost:8080
   networks:
     - network-spotia
   depends_on:
     mariadb-db:
       condition: service_healthy
     eureka-server:
       condition: service_healthy


 locales-service:
   build: ./locales/locales
   container_name: locales-service
   environment:
     SPRING_PROFILES_ACTIVE: dev
     EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
     DATABASE_HOST: mariadb-db
     GATEWAY_URL: http://localhost:8080
   networks:
     - network-spotia
   depends_on:
     mariadb-db:
       condition: service_healthy
     eureka-server:
       condition: service_healthy

 reservas-service:
   build: ./reservas/reservas
   container_name: reservas-service
   environment:
     SPRING_PROFILES_ACTIVE: dev
     EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
     DATABASE_HOST: mariadb-db
     GATEWAY_URL: http://localhost:8080
   networks:
     - network-spotia
   depends_on:
     mariadb-db:
       condition: service_healthy
     eureka-server:
       condition: service_healthy

 ubicaciones-service:
   build: ./ubicaciones/ubicaciones
   container_name: ubicaciones-service
   environment:
     SPRING_PROFILES_ACTIVE: dev
     EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
     DATABASE_HOST: mariadb-db
     GATEWAY_URL: http://localhost:8080
   networks:
     - network-spotia
   depends_on:
     mariadb-db:
       condition: service_healthy
     eureka-server:
       condition: service_healthy


networks:
 network-spotia:
   driver: bridge
